export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_VERIFICATION_PASSWORD = "CHANGE_VERIFICATION_PASSWORD";
export const SELECTED_DAY = "SELECTED_DAY";
